import type { Metadata } from "next";
import {  Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import ToasterProvider from "@/components/ToasterProvider";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin"],
});

const notoSerifBengaliMono = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} ${notoSerifBengaliMono.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar />
        <div className="sticky top-0 z-50 bg-white">
          <Marquee/>
        </div>
        
        <div className = "max-w-7xl mx-auto ">
           <ToasterProvider />
          {children}
          </div>
        
        <Footer/>
        </body>
    </html>
  );
}
